---
title: "search-index-ls-gh"
author: "Alex Papageorgiou"
date: "`r Sys.Date()`"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

```{r}
library(tidyverse)
library(reticulate)
library(lubridate)
library(ggthemes)
library(ragg)
library(ggtext)
library(stringr)

source("funcs.R")
```

## Read data

```{r}
df_full_api <- py_load_object(filename = "data/gen2/final_df_gapi_liveshop_10kseeds.pkl")

df_distinct_kw <- df_full_api %>%
  select(keyword, avg_monthly_searches, searches_past_months) %>%
  distinct(avg_monthly_searches, searches_past_months, .keep_all = TRUE)

```

## Read data

```{r}
live_shopping_search_dataset <- py_load_object(filename = "live_shopping_search_dataset.pkl")
```

## Parameters

```{r}
START_MONTH <- "2021-07-01"

PATTERN_SHOP <- "live shop|livestream shop|live commerce|live stream shop|livestream commerce|live stream commerce"

PATTERN_SELL <- "live sell"

month_levels <- format(
  seq(
    lubridate::ymd(START_MONTH),
    by = "month", 
    length.out = 48
  ),
  "%b %Y"
)
```

```{r}
# Bot activity detected
filter_out_list <- c(
  "eat to live shopping list", 
  "livestream shopping platforms", 
  "live shopping platform", 
  "live shopping platforms", 
  "livestream shopping platform", 
  "live stream shopping platform"
)

# 48 consecutive months starting July 2021
live_shop_related_df <- live_shopping_search_dataset %>% 
  filter(str_detect(keyword, PATTERN_SHOP)) %>%
  filter(lengths(searches_past_months) > 0) %>% 
  arrange(desc(avg_monthly_searches)) %>% 
  filter(avg_monthly_searches > 0) %>% 
  filter(!keyword %in% filter_out_list)

live_shop_longer <- live_shop_related_df %>% 
  unnest_longer(searches_past_months) %>% 
  ungroup()

months_vec <- seq(ymd(START_MONTH), by = "month", length.out = 48)

live_shop_all_by_month <- live_shop_longer %>%   
  mutate(month = rep(months_vec, len = nrow(live_shop_longer)))

live_shop_grouped_by_month <- live_shop_all_by_month %>%
  group_by(month) %>% 
  summarise(total_monthly_searches = sum(searches_past_months)) %>%
  mutate(
    month_label = format(month, "%m-%Y"),
    month_end = ceiling_date(month, "month") - days(1)
  )
```

## Search index 100 norm

```{r}
base_value <- live_shop_grouped_by_month$total_monthly_searches[1]

index_df <- live_shop_grouped_by_month %>%
  mutate(index_value = (total_monthly_searches / base_value) * 100)
```

## Live shop

```{r}
title_shop <- "Live Shopping Regains Momentum in 2025"

title_html <- str_replace(
  title_shop,
  regex("\\bLive Shopping\\b", ignore_case = TRUE),
  "<span style='font-weight:700; color:#CD0000; background-color:#gggggg; padding:1px 3px;'>\\0</span>"
)

sub_shop <- "Following a slowdown after Meta discontinued live shopping features in 2022-2023 
\nMetric: Search interest index for Live Shopping (LS)"
# sub_shop <- "INTERNAL USE: Unfiltered graph includes search volumes subject to potential bot activity in certain months"

caption_shop <- "\nIndex based on normalized U.S. search volume across 188 live shopping-related queries (July 2021 = 100). \nSource: Google Ads API (keyword planning service), July 2021-June 2025. Data retrieved July 2025. \nData, methodology & reproducible code: github.com/papageorgiou/live-shopping-research"
```

```{r}
# steelblue
ggplot(index_df, aes(x = month_end, y = index_value)) +
  geom_line(color = "red3", size = 1.5) + 
  geom_point(color = "red3", size = 2) +
  labs(
    title = title_html, 
    subtitle = sub_shop, 
    x = NULL, 
    y = NULL, 
    caption = caption_shop
  ) +
  scale_y_continuous(limits = c(0, NA)) + 
  ggthemes::theme_fivethirtyeight() +
  theme(
    plot.caption = element_text(hjust = 0, size=9, face="italic"),   # 0 = left, 0.5 = center, 1 = right
    plot.caption.position = "plot",           # place caption against the plot edge
    plot.title = element_markdown(lineheight = 1.05)
  )
```

```{r}
save_for_report(
  filename = "live_shopping_unfiltered_600dpi.png",  
  width_mm = 220, 
  height_mm = 130, 
  dpi = 600
)
```

## Annotations

```{r}
ggplot(index_df, aes(x = month_end, y = index_value)) +
  geom_line(color = "red3", size = 1.5) + 
  geom_point(color = "red3", size = 2) +
  labs(
    title = title_html, 
    subtitle = sub_shop, 
    x = NULL, 
    y = NULL, 
    caption = caption_shop
  ) +  
  scale_y_continuous(limits = c(0, NA)) + 
  ggthemes::theme_fivethirtyeight(base_size = 18) +
  geom_label(
    data = data.frame(
      x = as.Date(c("2022-08-29", "2023-06-01", "2023-11-08", "2024-12-29", "2025-06-05")),
      y = c(191.059805943972, 145.541005223885, 185.445648004049, 260.834895071852, 205),
      label = c(
        "8/22: Facebook ends LS", 
        "3/23: Instagram ends LS", 
        "9/23: Tiktok Shop \n launches in US", 
        "1/25: US Tiktok drama unfolds", 
        "5/25: QVC 24x7\nlive on TikTok"
      )
    ),
    mapping = aes(x = x, y = y, label = label),
    label.padding = unit(0.25, "lines"),
    label.r = unit(0.15, "lines"),
    inherit.aes = FALSE
  ) + 
  theme(
    plot.caption = element_text(hjust = 0, size=11, face="italic"),   # 0 = left, 0.5 = center, 1 = right
    plot.caption.position = "plot",           # place caption against the plot edge
    plot.title = element_markdown(lineheight = 1.05)
  )
```

```{r}
save_for_report(
  filename = "live_shopping_annot_600dpi.png",  
  width_mm = 250, 
  height_mm = 150, 
  dpi = 600
)
```

## Live sell

```{r}
live_sell_related_df <- live_shopping_search_dataset %>% 
  filter(str_detect(keyword, PATTERN_SELL)) %>%
  filter(lengths(searches_past_months) > 0) %>% 
  arrange(desc(avg_monthly_searches)) %>% 
  filter(avg_monthly_searches > 0) %>% 
  filter(!keyword %in% filter_out_list)

live_sell_longer <- live_sell_related_df %>% 
  unnest_longer(searches_past_months) %>% 
  ungroup()

months_vec <- seq(ymd(START_MONTH), by = "month", length.out = 48)

live_sell_all_by_month <- live_sell_longer %>%   
  mutate(month = rep(months_vec, len = nrow(live_sell_longer)))

live_sell_grouped_by_month <- live_sell_all_by_month %>%
  group_by(month) %>% 
  summarise(total_monthly_searches = sum(searches_past_months)) %>%
  mutate(
    month_label = format(month, "%m-%Y"),
    month_end = ceiling_date(month, "month") - days(1)
  )

base_value <- live_sell_grouped_by_month$total_monthly_searches[1]

index_df <- live_sell_grouped_by_month %>%
  mutate(index_value = (total_monthly_searches / base_value) * 100)
```

```{r}
# sub_sell <- "following a decline when Meta shut down Live Shopping features in 2022-3"

title_sell <- "Search Interest in Live Selling Has Grown Over 2x Since 2021"

caption_sell <- "\nIndex based on normalized U.S. search volume across 102 live selling-related queries (July 2021 = 100). \nSource: Google Ads API (keyword planning service), July 2021-June 2025. Data retrieved July 2025.\nData, methodology & reproducible code: github.com/papageorgiou/live-shopping-research"
```

```{r}
# Plot the composite index with the first month set to 100
ggplot(index_df, aes(x = month, y = index_value)) +
  geom_line(color = "steelblue", size = 1) + 
  geom_point(color = "steelblue") +
  labs(
    title = title_sell, 
    subtitle = NULL, 
    x = NULL, 
    y = NULL, 
    caption = caption_sell
  ) +  
  scale_y_continuous(limits = c(0, NA)) + 
  ggthemes::theme_fivethirtyeight() + 
  theme(
    plot.caption = element_text(hjust = 0),   # 0 = left, 0.5 = center, 1 = right
    plot.caption.position = "plot"            # place caption against the plot edge
  )
```

```{r}
save_for_report(
  filename = "live_sell_600dpi.png",  
  width_mm = 220, 
  height_mm = 130, 
  dpi = 600
)
```

## To CSV

```{r}
# live_shop_related_to_csv <- live_shop_related_df %>% 
#   mutate(
#     searches_past_months = map_chr(
#       searches_past_months, 
#       function(x) paste(x, collapse = ", ")
#     )
#   ) %>% 
#   rename(searches_past_48_months = searches_past_months)
# 
# write_csv(live_shop_related_to_csv, "live_shop_related.csv")
```



